version: '0.0.1'

services:
  postgres_dev:
    container_name: postgres_dev
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api_dev
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        PIPENV_DEV: "True"
    env_file:
      - .env.local
    environment:
      MODULE_NAME: src.app
      PYTHONPATH: "/app/api/src"
    ports:
      - 80:80
    depends_on:
      postgres_dev:
        condition: service_healthy
    volumes:
      - ./api:/app
    

volumes:
  postgres_dev: