name: Build API

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check Docker Login
        if: steps.docker_login.outcome == 'failure'
        run: |
          echo "Failed to log in to Docker Hub. Please check your credentials."
          exit 1
